### ISSUE TITLE
ISC License.txt is missing!

### ISSUE THREAD

**Issue by C3P0R2D** [Atticweb/node-js-connect4#2]
Hi! I saw in package.json the code is licensed as ISC but after some reading I found this is not applicable unless the ISC license.txt is placed in the root directory.

The reason I point this out is that I am creating a connect-4 clone and want to use the HTML/CSS structure, but no license file makes me kind of uneasy.

Would you consider uploading a license.txt?
Thanks

**Comment by Jaapze** [comment]
I added a License file with a MIT License, thanks for the message. Good luck with your project!
